// Generated by scripts/ui-library/register.mjs from next-templates/*/components/hairline: do not edit.

/** The templates that use each component, and the section it's in. */
export const USED_IN: Record<string, { template: string; where: string }[]> = {
  'number-roll': [
    { template: 'cutroom', where: 'Pricing calculator' },
    { template: 'emberline', where: 'Pricing' },
    { template: 'halftone', where: 'Pricing' },
    { template: 'influence', where: 'Pricing' },
    { template: 'prism', where: 'Pricing' },
    { template: 'relay', where: 'Pricing' },
    { template: 'shear', where: 'Bill chart' },
    { template: 'shear', where: 'Feature visual' },
    { template: 'shear', where: 'Benefits' },
    { template: 'shear', where: 'Features' },
    { template: 'shear', where: 'Proof' },
    { template: 'shear', where: 'Teams' },
    { template: 'shear', where: 'Testimonials' },
    { template: 'tempo', where: 'Pricing' },
  ],
  'text-morph': [
    { template: 'cutroom', where: 'Pricing calculator' },
    { template: 'emberline', where: 'Pricing' },
    { template: 'footnote', where: 'Sign-up' },
    { template: 'halftone', where: 'Pricing' },
    { template: 'influence', where: 'Pricing' },
    { template: 'kept', where: 'Sign-up' },
    { template: 'parley', where: 'Sign-up' },
    { template: 'prism', where: 'Pricing' },
    { template: 'relay', where: 'Pricing' },
    { template: 'shear', where: 'Step scene' },
    { template: 'shear', where: 'Signup form' },
    { template: 'shear', where: 'Teams' },
    { template: 'stillform', where: 'Shot selector' },
    { template: 'tempo', where: 'Pricing' },
  ],
  'faq-accordion': [
    { template: 'shear', where: 'Faq' },
  ],
  'logo-marquee': [
    { template: 'shear', where: 'Hero' },
  ],
  'pricing-toggle': [
    { template: 'shear', where: 'Pricing' },
  ],
};
