// Generated by scripts/ui-library/register.mjs from next-templates/*/components/hairline: do not edit.

/** The templates that use each component, and the section it's in. */
export const USED_IN: Record<string, { template: string; where: string }[]> = {
  'number-roll': [
    { template: 'cutroom', where: 'Pricing calculator' },
    { template: 'emberline', where: 'Pricing' },
    { template: 'halftone', where: 'Pricing' },
    { template: 'influence', where: 'Pricing' },
    { template: 'prism', where: 'Pricing' },
    { template: 'relay', where: 'Pricing' },
    { template: 'tempo', where: 'Pricing' },
  ],
  'text-morph': [
    { template: 'cutroom', where: 'Pricing calculator' },
    { template: 'emberline', where: 'Pricing' },
    { template: 'footnote', where: 'Sign-up' },
    { template: 'halftone', where: 'Pricing' },
    { template: 'influence', where: 'Pricing' },
    { template: 'kept', where: 'Sign-up' },
    { template: 'parley', where: 'Sign-up' },
    { template: 'prism', where: 'Pricing' },
    { template: 'relay', where: 'Pricing' },
    { template: 'stillform', where: 'Shot selector' },
    { template: 'tempo', where: 'Pricing' },
  ],
};
