import type { UiItem } from '../registry';
import { numberRoll } from './number-roll';
import { pricingToggle } from './pricing-toggle';
import { promptComposer } from './prompt-composer';
import { mentionMenu } from './mention-menu';
import { attachmentChip } from './attachment-chip';
import { modeSwitcher } from './mode-switcher';
import { modelPicker } from './model-picker';
import { voiceInput } from './voice-input';
import { thinkingIndicator } from './thinking-indicator';
import { thinkingTrace } from './thinking-trace';
import { toolCall } from './tool-call';
import { clarifyingQuestion } from './clarifying-question';
import { approvalCard } from './approval-card';
import { plan } from './plan';
import { webResearch } from './web-research';
import { commandOutput } from './command-output';
import { taskProgress } from './task-progress';
import { streamingAnswer } from './streaming-answer';
import { codeBlock } from './code-block';
import { citation } from './citation';
import { responseVersions } from './response-versions';
import { selectionActions } from './selection-actions';
import { diffReview } from './diff-review';
import { actionReceipt } from './action-receipt';
import { chatNotice } from './chat-notice';
import { usageMeter } from './usage-meter';
import { chatScroll } from './chat-scroll';
import { messageEdit } from './message-edit';
import { chatHistory } from './chat-history';

/** Order within each group is the order on /ui. */
export const items: UiItem[] = [numberRoll, pricingToggle, promptComposer, mentionMenu, attachmentChip, modeSwitcher, modelPicker, voiceInput, thinkingIndicator, thinkingTrace, toolCall, clarifyingQuestion, approvalCard, plan, webResearch, commandOutput, taskProgress, streamingAnswer, codeBlock, citation, responseVersions, selectionActions, diffReview, actionReceipt, chatNotice, usageMeter, chatScroll, messageEdit, chatHistory];
