export const siteConfig = {
  name: "Drawgle",
  baseUrl: "https://drawgle.com",
  defaultTitle: "AI Mobile App Designer | Design App UIs in Minutes",
  defaultDescription:
    "AI mobile app designer for devs who can't design. Turn text or screenshots into Premium Mobile UIs. Export clean Tailwind HTML + Agent Packs.",
  supportEmail: "support@drawgle.com",
  creatorHandle: "@9to5_Dad",
  sameAs: ["https://x.com/9to5_Dad"],
  defaultOgImage: {
    path: "og-image.webp",
    width: 1200,
    height: 630,
    alt: "Drawgle AI mobile app UI designer",
  },
  keywords: [
    "AI mobile app UI designer",
    "AI mobile UI design",
    "app UI generator",
    "screenshot to editable UI",
    "mobile app design",
    "mobile design tokens",
    "agent-ready UI handoff",
    "HTML Tailwind export",
  ],
  publicRoutes: [
    {
      path: "/",
      title: "AI Mobile App UI Designer for Modern Apps | Drawgle",
      description:
        "Design editable mobile app UI from prompts, screenshots, or visual references. Keep screens consistent with shared tokens and export Tailwind HTML plus an Agent Pack.",
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      path: "/pricing",
      title: "AI Mobile UI Designer Pricing | Drawgle",
      description:
        "Compare Drawgle plans for prompt-to-UI generation, screenshot reconstruction, editable design tokens, Tailwind HTML, and Agent Pack exports.",
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      path: "/showcase",
      title: "AI-Generated Mobile UI Showcase",
      description:
        "Explore premium mobile app screens generated by Drawgle across finance, commerce, fitness, productivity, security, and more.",
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      path: "/terms",
      title: "Terms of Service",
      description: "Terms governing your use of Drawgle's AI mobile UI design service.",
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      path: "/privacy-policy",
      title: "Privacy Policy",
      description: "How Drawgle collects, uses, stores, and protects personal data.",
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      path: "/refunds-policy",
      title: "Refund Policy",
      description: "Drawgle's policy for subscription cancellations, refund requests, and AI credits.",
      changeFrequency: "monthly",
      priority: 0.4,
    },
  ] as const,
  pricing: [
    {
      name: "Starter",
      description: "For builders exploring prompt-to-UI and screenshot-to-UI workflows.",
      price: "9",
      currency: "USD",
      url: "/pricing",
    },
    {
      name: "Pro",
      description: "For creators producing larger mobile UI projects with complete HTML exports and Agent Packs.",
      price: "29",
      currency: "USD",
      url: "/pricing",
    },
    {
      name: "Studio",
      description: "For teams and power users with high-volume mobile UI generation needs.",
      price: "79",
      currency: "USD",
      url: "/pricing",
    },
  ] as const,
} as const;

export type PublicRoutePath = (typeof siteConfig.publicRoutes)[number]["path"];

export function absoluteUrl(path = "/") {
  return new URL(path, siteConfig.baseUrl).toString();
}
