import type { ProblemSummary, PublicTrafficStats } from "./types"

export const MOCK_TRAFFIC: PublicTrafficStats = {
  total_visitors: 18420,
  total_days: 14,
}

export const MOCK_PROBLEMS: ProblemSummary[] = [
  {
    id: "p1",
    slug: "salesforce-opaque-contract-lockin",
    statement: "Annual renewal invoices jump 25% with zero added value and opaque line items nobody can explain.",
    target_product_name: "Salesforce",
    switch_condition: "Transparent month-to-month pricing with zero-click HubSpot or Pipedrive contact migration.",
    category: "CRM & Sales",
    origin: "curated",
    support_count: 342,
    answer_count: 4,
    supports_24h: 38,
    trending_score: 95,
    answers: [
      {
        offer_id: "a1",
        product_id: "attio",
        name: "Attio",
        registrable_domain: "attio.com",
        destination_url: "https://attio.com",
        tagline: "The modern CRM built for speed and real-time collaboration",
        solves_text: "Clear transparent tiers with automatic data deduplication and full API access.",
        switch_incentive: "50% off for your first 6 months when switching from Salesforce.",
        verified: true,
      },
      {
        offer_id: "a2",
        product_id: "folk",
        name: "Folk CRM",
        registrable_domain: "folk.app",
        destination_url: "https://folk.app",
        tagline: "All-in-one CRM for teams that value simplicity",
        solves_text: "Contact intelligence without enterprise bloat.",
        switch_incentive: "Free migration service with dedicated onboarding specialist.",
        verified: true,
      },
    ],
    created_at: "2026-03-12T10:00:00Z",
  },
  {
    id: "p2",
    slug: "jira-clunky-navigation-load-times",
    statement: "Clicking an issue card takes 4 full seconds to open. Filters and custom fields have turned our board into a swamp.",
    target_product_name: "Jira Software",
    switch_condition: "Instant sub-100ms keyboard navigation with linear issue IDs and simple git hooks.",
    category: "Project Management",
    origin: "curated",
    support_count: 512,
    answer_count: 3,
    supports_24h: 62,
    trending_score: 98,
    answers: [
      {
        offer_id: "a3",
        product_id: "linear",
        name: "Linear",
        registrable_domain: "linear.app",
        destination_url: "https://linear.app",
        tagline: "The issue tracking tool you'll actually enjoy using",
        solves_text: "Sub-50ms sync engine, offline support, and natural cycle management.",
        switch_incentive: "One-click Jira cloud importer brings over all sprints, tasks, and attachments.",
        verified: true,
      },
    ],
    created_at: "2026-03-15T14:20:00Z",
  },
  {
    id: "p3",
    slug: "hubspot-marketing-contact-tier-tax",
    statement: "HubSpot charges for every unengaged email in your database even if you haven't emailed them in a year.",
    target_product_name: "HubSpot",
    switch_condition: "Pay only for active monthly sends, with unlimited dormant contact storage.",
    category: "Marketing Automation",
    origin: "user",
    support_count: 278,
    answer_count: 2,
    supports_24h: 21,
    trending_score: 87,
    answers: [
      {
        offer_id: "a4",
        product_id: "loops",
        name: "Loops.so",
        registrable_domain: "loops.so",
        destination_url: "https://loops.so",
        tagline: "Email for modern SaaS companies",
        solves_text: "Clean transactional and marketing email without inflated seat taxes.",
        switch_incentive: "3 months free for startups under $2M ARR.",
        verified: true,
      },
    ],
    created_at: "2026-03-20T09:15:00Z",
  },
  {
    id: "p4",
    slug: "aws-unpredictable-data-transfer-egress",
    statement: "Egress data transfer costs are deliberately hidden behind NAT Gateway and cross-AZ line items on the invoice.",
    target_product_name: "AWS",
    switch_condition: "Predictable flat monthly bandwidth limits with transparent zero-egress policies.",
    category: "Cloud Infrastructure",
    origin: "user",
    support_count: 419,
    answer_count: 2,
    supports_24h: 49,
    trending_score: 91,
    answers: [
      {
        offer_id: "a5",
        product_id: "hetzner",
        name: "Hetzner Cloud",
        registrable_domain: "hetzner.com",
        destination_url: "https://hetzner.com",
        tagline: "Dedicated power and cloud performance at European prices",
        solves_text: "20TB free traffic included on every cloud instance with zero surprise charges.",
        switch_incentive: "$50 free starting cloud credit for new developers.",
        verified: true,
      },
    ],
    created_at: "2026-03-22T16:45:00Z",
  },
  {
    id: "p5",
    slug: "quickbooks-slow-export-cluttered-ui",
    statement: "Generating a simple P&L balance sheet takes minutes and requires navigating 8 submenus of upsells.",
    target_product_name: "QuickBooks",
    switch_condition: "Instant real-time ledger with automated receipt OCR and double-entry reconciliation.",
    category: "Accounting & Finance",
    origin: "curated",
    support_count: 198,
    answer_count: 1,
    supports_24h: 18,
    trending_score: 79,
    answers: [
      {
        offer_id: "a6",
        product_id: "puzzle",
        name: "Puzzle.io",
        registrable_domain: "puzzle.io",
        destination_url: "https://puzzle.io",
        tagline: "Autonomous accounting for high-growth startups",
        solves_text: "Automated GAAP financial statements generated in real time directly from bank feeds.",
        switch_incentive: "Free financial review and migration from QuickBooks.",
        verified: true,
      },
    ],
    created_at: "2026-03-25T11:30:00Z",
  },
  {
    id: "p6",
    slug: "intercom-surprise-seat-pricing-calculator",
    statement: "Fin bot resolution fees billed unexpectedly at $0.99 per question even when it answers 'I do not know'.",
    target_product_name: "Intercom",
    switch_condition: "Flat monthly support fee with zero resolution penalties and open LLM bring-your-own-key option.",
    category: "Customer Support",
    origin: "user",
    support_count: 367,
    answer_count: 0,
    supports_24h: 44,
    trending_score: 93,
    answers: [],
    created_at: "2026-03-27T08:00:00Z",
  },
]
